project_id = "jbvvujcdlvcrhnxvnfka"

[functions.webhook-lead]
verify_jwt = false

[functions.ai-landing-page]
verify_jwt = false

[functions.book-appointment]
verify_jwt = false

[functions.ai-content-gen]
verify_jwt = false

[functions.lms-webhook]
verify_jwt = false

[functions.social-publish]
verify_jwt = false
